# Cipher Configuration
# ---
# If changed, project WILL STOP working, there is NO WAY AROUND if keys are lost or changed!
# Do NOT change these keys at ANY POINT AFTER INITIALISATION OF PROJECT! DO NOT!

# Primary Cipher Key
primary: "hello World"
# Secondary Key
secondary: "hello World"
# Users models encryption
users: "hello World"
# Project models encryption
project: "hello World"
# Misc encryption
misc: "hello World"
