# Cipher Configuration
# ---
# If changed, project WILL STOP working, there is NO WAY AROUND if keys are lost or changed!
# Do NOT change these keys at ANY POINT AFTER INITIALISATION OF PROJECT! DO NOT!

# Primary Cipher Key
primary: "some random words or PRNG entropy here"
# Secondary Key
secondary: "some random words or PRNG entropy here"
# Users models encryption
users: "some random words or PRNG entropy here"
# Project models encryption
project: "some random words or PRNG entropy here"
# Misc encryption
misc: "some random words or PRNG entropy here"
