# Cipher Configuration
# ---
# If changed, project WILL STOP working, there is NO WAY AROUND if keys are lost or changed!
# Do NOT change these keys at ANY POINT AFTER INITIALISATION OF PROJECT! DO NOT!

# Primary Cipher Key
primary: "helloWorld"
# Secondary Key
secondary: "helloWorld"
# Users models encryption
users: "helloWorld"
# Project models encryption
project: "helloWorld"
# Misc encryption
misc: "helloWorld"
